site_name: "Monolith to Event-Driven Architecture"
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-S9M1J6BX7L

extra_css:
  - stylesheets/extra.css

nav:
  - Getting Started: index.md
  - Our Goal: goal.md
  - Benefits: benefits.md
  - Tools: tools.md
  - Terraform: terraform.md
  - Sending messages from Ruby to SNS: ruby_sdk.md
  - About the author: author.md
  - Cover Art: cover_art.md
  